---
title: Your awesome title
timezone: UTC
collections:
  my_collection:
    title: My Collection
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout: foo
email: your-email@domain.com
description: hello
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
sass:
  sass_dir: styles
include:
- _pages
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
